"""empty message

Revision ID: 473245d615a7
Revises: 23244fd21d80
Create Date: 2020-03-14 23:59:10.023407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473245d615a7'
down_revision = '23244fd21d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'photo')
    # ### end Alembic commands ###
